version: '3.7'
services:
  postgres:
      image: postgres:13.2-alpine
      container_name: postgres
      ports:
          - 5432:5432
      volumes:
          - postgres_volume:/var/lib/postgresql/data
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      hostname: postgres
      restart: always
      user: root
  pgadmin4:
        image: dpage/pgadmin4:5.0
        container_name: pgadmin4
        ports:
            - 8000:80
        volumes:
            - pgadmin4_volume:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: root
            PGADMIN_DEFAULT_PASSWORD: root
        hostname: pgadmin4
        depends_on:
          - postgres
        restart: always

volumes:
  postgres_volume:
    external: true
  pgadmin4_volume:
    external: true